Update daal version and naming
conda-forge/intel_repack-feedstock pull request #18
Opened 2020-12-03 09:46 UTC by Pahandrovich

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

2020-12-03 09:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

For **recipe**:

 * It looks like the 'daal' output doesn't have any tests.
 * It looks like the 'daal-include' output doesn't have any tests.
 * It looks like the 'daal-static' output doesn't have any tests.
 * It looks like the 'daal-devel' output doesn't have any tests.

2020-12-03 09:57 UTC, napetrov commented on recipe/meta.yaml
> +    script: repack.sh   # [unix]
I don't think we need to call repack for this empty metapackage

2020-12-03 12:26 UTC, beckermr requested changes
Some of the run exports here look a little funny. The `daal` doesn't need a run export on `dal` since the original `daal` package didn't have any run exports.

2020-12-04 11:20 UTC, beckermr requested changes
It looks like you cleared the run requirements when you should have cleared the run_export sections.

2020-12-04 11:24 UTC, napetrov commented on recipe/meta.yaml
> +{% set buildnum = "0" %}  # [linux]
we have buildnums avaialbe now. 
But we anyway need need new TBB in conda-forge first.

2020-12-16 23:28 UTC, PetrovKP commented
I think REAMDE needs to be updated

2021-02-26 08:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

2021-03-05 10:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-03-05 10:46 UTC, napetrov commented
@conda-forge-admin, please rerender

2021-03-05 10:47 UTC, napetrov commented on recipe/meta.yaml
> +    sha256:
Let's remove sha256 field. It can't be empty

2021-03-05 10:49 UTC, napetrov commented on recipe/meta.yaml
>        home: https://software.intel.com/en-us/daal
Please pickup new names links - as example https://github.com/conda-forge/intel_repack-feedstock/pull/14

2021-03-30 18:38 UTC, isuruf commented
Ping on this @Pahandrovich

2021-03-31 09:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

2021-03-31 12:34 UTC, napetrov commented
@conda-forge-admin, please rerender

2021-04-02 15:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

2021-04-05 09:42 UTC, napetrov approved these changes

2021-04-05 09:42 UTC, napetrov commented
@isuruf  - thanks for update and fixes. 
I think this is ready to go now

2021-04-05 14:38 UTC, merged